songs.push = (
{title:"Kimcil Kepolen",src:"",emoji:"😅"},
{title:"Sayang",src:"",emoji:"🥺"},
{title:"Nemen",src:"",emoji:"💔"},
{title:"Talining Asmoro",src:"",emoji:"💕"},
{title:"Kelingan Mantan",src:"",emoji:"😔"},
{title:"Pamit",src:"",emoji:"👋"},
{title:"Ra Kuat Mbok",src:"",emoji:"😭"},
{title:"Aku Cah Kerjo",src:"",emoji:"💼"},
{title:"Ojo Nesu Nesu",src:"",emoji:"😅"},
{title:"Isin",src:"",emoji:"🙈"},
{title:"Rembulan",src:"",emoji:"🌙"},
{title:"Tulung",src:"",emoji:"🙏"},
{title:"Yowes Modaro",src:"",emoji:"🤷"},
{title:"Bojomu Semangatku",src:"",emoji:"💞"},
{title:"Kependem Tresno",src:"",emoji:"🤐❤️"},
{title:"Loro Ati",src:"",emoji:"💔"},
{title:"Salah Roso",src:"",emoji:"😶"},
{title:"Tresno Tekan Mati",src:"",emoji:"🖤"},
{title:"Mergo Sayang",src:"",emoji:"❤️"},
{title:"Lintang Ati",src:"",emoji:"✨"},
{title:"Tak Ikhlasno",src:"",emoji:"🥲"},
{title:"Cinta Tak Direstui",src:"",emoji:"🚫❤️"},
{title:"Janji Palsu",src:"",emoji:"💢"},
{title:"Kok Iso Yo",src:"",emoji:"🤔"},
{title:"Lungamu Ninggal Kenangan",src:"",emoji:"🥀"},
{title:"Mantan Tersayang",src:"",emoji:"💘"},
{title:"Tresno Waranggono",src:"",emoji:"🎶"},
{title:"Sebatas Friendly",src:"",emoji:"🙂"},
{title:"Ropang",src:"",emoji:"🍞🔥"}
)